{
  "input": {
    "lug": {
      "number": "1",
      "height": "1",
      "width_plate": "0.5",
      "length_lug": "1",
      "thickness_plate": "1",
      "thickness_lug": "1",
      "material": "1",
      "density": "1",
      "lug_spacing": "0.5",
      "hole_diameter": "0.4",
      "allowable_stress": "520000000"
    },
    "fastener": {
      "inner_diameter": "0.03",
      "outer_diameter": "0.04",
      "number": "2",
      "coord_list": "[[2, 2], [3, 1], [1, 4], [8, 4]]",
      "edge_horizontal": "0.05",
      "edge_vertical": "0.06",
      "horizontal_spacing": "0.06",
      "material": "1",
      "density": "1"
    },
    "vehicle_wall": {
      "thickness": "1",
      "allowable_stress": "50000000"
    }
  },
  "output": {
    "plate": {},
    "fastener": {
      "quantity": "12"
    }
  }
}